In [1]:
import numpy as np #question 1
arr = np.array([1,2,3,4]);
print(arr);

[1 2 3 4]


In [17]:
import numpy as np #question 2
arr = np.full((6,5),4);
print(arr);

[[4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]]


In [25]:
import numpy as np #question 3
arr = np.identity(3);
print(arr);

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [19]:
import numpy as np #question 4
arr = np.full((10,10),7);
print(arr);

[[7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7]]


In [65]:
import numpy as np #question 5
arr = np.eye(5);
print(arr);
print(arr[:,:]);
print(arr[2:5,0:3]);
print(arr[0:2,0:5]);
print(arr[2:4,2:4]);
print(arr[-3:-1,-3:-1]);
print(arr[-4:-1,-4:-1]);


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]]
[[1. 0.]
 [0. 1.]]
[[1. 0.]
 [0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [63]:
import numpy as np #question 6
arr = np.array([[[1,2,3],[3,4,5],[6,7,7]]]);
print(arr);
print("The Dimensions are : ", np.ndim(arr));

[[[1 2 3]
  [3 4 5]
  [6 7 7]]]
The Dimensions are :  3


In [100]:
import numpy as np #question 7
arr = np.array([2,2,2,2], ndmin=8);
print(arr)


[[[[[[[[2 2 2 2]]]]]]]]
